#!/bin/bash

HOME=/home/opencv

function log_info() {
  echo
  echo $1
  echo
}

function clean_samples() {
  cd $HOME/samples
  rm -rf java/build
  rm -rf java/java.log
}

function validate_test_log() {
  if ! grep -q "$1" $2; then exit 1; fi
}

function run_java_test() {
  log_info "Running java health check."

  cd $HOME/samples/java

  ant -DopencvJarPath=$OPENCV_JAVA_BINARY_PATH \
      -DopencvLibraryPath=$OPENCV_JAVA_LIBRARY_PATH rebuild-run | tee java.log

  validate_test_log 'BUILD SUCCESSFUL' 'java.log'
}

main() {
  run_java_test
  clean_samples
  log_info "Health check successful!"
}

main "$@"
